apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment
  template:
    spec:
      containers:
        - name: main-container
          image: app-image
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: config
          ports:
            - containerPort:
                valueFrom:
                  configMapKeyRef:
                    name: config
                    key: PORT
          resources:
            requests:
              memory: "1024Mi"
            limits:
              memory: "1024Mi"
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  PORT: 5000
