apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment
  template:
    spec:
      containers:
        - name: main-container
          image: app-image:latest
          envFrom:
            - configMapRef:
                name: config
          ports:
            - containerPort: 5000
              name: app-port
          resources:
            requests:
              memory: "128Mi"
            limits:
              memory: "128Mi"
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  PORT: "5000"
