apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment
  template:
    spec:
      containers:
        - name: main-container
          image: app-image
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "5000"
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "1024Mi"
            limits:
              memory: "1024Mi"
      imagePullSecrets:
        - name: regcred
