apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    spec:
      containers:
        - name: app
          image: app-image
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "3000"
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "1024Mi"
            limits:
              memory: "1024Mi"
      imagePullSecrets:
        - name: regcred
