apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: ingress
spec:
  rules:
    - host: host
      http:
        paths:
          - path: /
            backend:
              service:
                name: service
                port:
                  number: 80
