apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/terion-name/k8s-templates.git/packs/default_https/
  {{#added_resources}}
  - {{{.}}}
  {{/added_resources}}
replacements:
  - path: https://raw.githubusercontent.com/terion-name/k8s-templates/master/helpers/host-replacement.yml
namespace: {{{namespace}}}
namePrefix: {{{appname}}}-
commonLabels:
  app: {{{appname}}}
  host: {{{host}}}
images:
  - name: app-image
    newTag: {{{tag}}}{{^tag}}latest{{/tag}}
    newName: {{{image}}}
{{#port}}
patches:
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/ports/0/containerPort
        value: {{port}}
 {{/port}}
{{#merge}}
patchesStrategicMerge:
  - {{{merge}}}
{{/merge}}
{{#env}}
configMapGenerator:
  - name: config
    behavior: merge
    envs:
      - {{{env}}}
{{/env}}
