apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/terion-name/k8s-templates.git/packs/default_https/
replacements:
  - path: https://raw.githubusercontent.com/terion-name/k8s-templates/master/helpers/host-replacement.yml
  - path: https://raw.githubusercontent.com/terion-name/k8s-templates/master/helpers/port-replacement.yml
namespace: {{namespace}}
namePrefix: {{appname}}-
commonAnnotations:
  appPort: {{port}}{{^port}}5000{{/port}}
commonLabels:
  app: {{appname}}
  host: {{host}}
images:
  - name: app-image
    newTag: {{tag}}{{^tag}}latest{{/tag}}
    newName: {{image}}
{{#env}}
configMapGenerator:
  - name: config
    behavior: merge
    envs:
      - {{env}}
{{/env}}
